### ISSUE TITLE
Download failed

### ISSUE THREAD

**Issue by iwkse** [cetra3/onlyoffice-alfresco#1]
Hi,
I'm testing this integration and right now I was not able to make it works. When OnlyOffice document server opens the files I get a window with and error, download failed.
I'm using the docker and running it with maven (so not yet deployed on a server)
Do you have an idea?
Regards

[edit]
I think it's related to that. I'm checking OnlyOffice logs and that seems to be the case. I'm trying to deploy to a test server and after I will close this ticket.

**Comment by cetra3** [comment]
You will need onlyoffice to talk directly to Alfresco, so as long as you have the external domain set correctly in Alfresco, this should work.  The relevant global property is `alfresco.host`
