### ISSUE TITLE
Unable to find valid certification path

### ISSUE THREAD

**Issue by iwkse** [cetra3/onlyoffice-alfresco#14]
Hi, I've setup both alfresco and onlyoffice with SSL certificates and the content is not updated on alfresco and it's showing this error:

ERROR [com.parashift.onlyoffice.CallBack] [http-bio-8443-exec-10] javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to      find valid certification path to requested target

Certificates are not self-signed but create on letsencrypt

Do you have any idea why I get this error?

**Comment by iwkse** [comment]
It was something unrelated. Upgrading letsencrypt changed the key file name.
Working great now!

**Comment by cetra3** [comment]
Ah, all good!
