### ISSUE TITLE
Plugin don't work if Alfresco run on SSL

### ISSUE THREAD

**Issue by massimone73** [cetra3/onlyoffice-alfresco#15]
Hello,
My Alfresco installation does not work with onlyoffice plugin.
This is because Alfresco uses SSL with Apache 2 and mod_jk, and alfresco-global.properties is set to:

alfresco.port=443
alfresco.protocol=https
share.port=443
share.protocol=https

you can use Alfresco onlyoffice plugin in SSL mode?
Thank you.

**Comment by cetra3** [comment]
Hi @massimone73 , 

You can definitely use this with SSL. It's how we have it configured in our environment. There might be a couple of things that could go wrong:

* Only office needs to use SSL also. This is because browsers don't allow insecure connections from an SSL session
* Only office needs to be able to connect to Alfresco to download the document. 
* Alfresco needs to be able to connect to Only office to download changes
* Your browser needs to be able to talk to both

If you enable debug logs to `com.parashift`  you should be able to see what's happening. You may want to look at the browser developer console to see if there are any errors.

**Comment by massimone73** [comment]
Hi,
I do not know how to enable debugging logs to com.parashift.
Please, could you tell me the procedure?

I installed Onlyoffice Document Server by Docker on a VM Ubuntu 16.04 LTS 64-Bit and I created SSL certificates by Let's Encrypt.
I started onlyoffice so laps on port 443 and actually I connect safely through both the url of onlyoffice that by Alfresco.

Unfortunately, after having opened and edited properly any Alfresco document through Onlyoffice, I can not save it. The icon of the disk appears to be disabled.

The VMs on which it is installed Alfresco communicates properly with the VM Onlyoffice, I also manually set the IP addresses and host names of both the respective /etc/hosts file.

Any suggestions?

Thank you.

**Comment by cetra3** [comment]
Hi @massimone73,

You save it by closing the window.  This will unlock the document and trigger a change back to Alfresco.

Instructions for enabling debug logs are here: http://docs.alfresco.com/5.1/tasks/log-levels-set.html

**Comment by massimone73** [comment]
Do not save!

If alfresco-global.properties imposed on the following parameters:

alfresco.port = 8080
alfresco.protocol = http
share.port = 8080
share.protocol = http

and then I access from the browser to the following url:

http://my.domain.com:8080/share/page

the plugin onlyoffice-alfresco works perfectly.

While if the reimposed alfresco-global.properties file with the following parameters:

alfresco.port = 443
alfresco.protocol = https
share.port = 443
share.protocol = https

It is not saved anything.

Unfortunately still do not understand how to turn the logs on com.parashift.

**Comment by seky739** [comment]
Hello for me work perfectly. I have docker container and alfresco on same machine and work.  My setup is 
alfresco.context=alfresco
alfresco.port=443
alfresco.protocol=https

share.context=share
share.port=443
share.protocol=https

Do you include your certificates to both instances? I mean alfresco server and docker container (nginx -ssl). I have problem's with SSL too but Certificate solve it.

**Comment by angelborroy-ks** [comment]
For me it's working, just added OnlyOffice SSL certificate to alfresco Java `cacerts` keystore.
