### ISSUE TITLE
Cant open document in onlyoffice from alfresco

### ISSUE THREAD

**Issue by tamim74** [cetra3/onlyoffice-alfresco#16]
I have a question.
I wanted to integrate alfresco with onlyoffice. I have installed alfresco community 5.2 in a linux machine and installed the onlyoffice integration edition document server in another windows machine. Now how do I connect onlyoffice from alfresco? what should be the URL which needs to be put into alfresco property file?

I tried to follow the official documentation. But that is applicable when both alfresco and document server is installed in same machine. What happens when they are in different machines?

Can you help me please?

**Comment by cetra3** [comment]
@tamim74,

The instructions in the [readme](https://github.com/cetra3/onlyoffice-alfresco#alfresco) are for having Alfresco and OnlyOffice on different machines.

For Alfresco to OnlyOffice, it uses the  `onlyoffice.url` global config.  For OnlyOffice to Alfresco it uses the following attributes:

```
alfresco.protocol=http
alfresco.host=alfresco.yourcompany.local
alfresco.port=8080
alfresco.context=alfresco
```

Please read through the readme again and let me know if it doesn't make sense, and I can update the documentation.

**Comment by tamim74** [comment]
@cetra3 
If onlyoffice document server is installed in another machine,
onlyoffice.url = http://documentserver/
is not accessible from the alfresco machine. Do I need to change anything there?

**Comment by cetra3** [comment]
Both Alfresco and OnlyOffice don't need to be on the same machine, but they do need to be able to access eachother via HTTP and both need valid DNS names (or a configured /etc/host file)

**Comment by tamim74** [comment]
I did not get it. When I try to hit the  **http://documentserver/** url, I get DNS address could not be found. But I can access the onlyoffice welcome page from the alfresco machine.
How do I resolve this?
Another question I have is how do we generate  **onlyoffice.token** ? Or can this be any secret code?

**Comment by cetra3** [comment]
Sounds like you need to adjust your dns settings according to the correct hostname of the server.  

`onlyoffice.token` can be anything

**Comment by tamim74** [comment]
hi @cetra3 
now the problem I am facing is when I edit a **my file** document, I can see the latest changes both in alfresco and onlyoffice. But when I try to change a shared file, the latest changes are only available in onlyoffice, latest changes are not getting reflected in alfresco.

What I am missing here?

alfresco-globalproperty file reads as:

alfresco.context=alfresco
alfresco.host=host
alfresco.port=port
alfresco.protocol=http

share.context=share
share.host=host
share.port=port
share.protocol=http

**Comment by cetra3** [comment]
alfresco.host needs to be equal to the hostname of the alfresco instance you're running.  Same with alfresco.port (by default this is port 8080)
