### ISSUE TITLE
Alfresco 5.2.f + OO

### ISSUE THREAD

**Issue by pixel75** [cetra3/onlyoffice-alfresco#18]
I tried to integrate Alfresco Community with Onlyoffice Community so I download the source.
In repo folder I changed in build.gradle:
 alfresco.version = "5.0.d" -> alfresco.version = "5.2.f"
but the build failed with this error:
> Task :compileJava
/root/onlyoffice-alfresco/repo/src/main/java/com/parashift/onlyoffice/CallBack.java:33: error: package javax.servlet.http does not exist
import javax.servlet.http.HttpServletRequest;
                         ^
1 error

> Task :compileJava FAILED

FAILURE: Build failed with an exception.

Any ideas?

**Comment by cetra3** [comment]
This is probably due to some transient dependencies not being included in the new version.  

You are be able to use this module as it stands with `5.2.f`

**Comment by pixel75** [comment]
I installaed the AMP 1.05

and modified the 
/alfresco/tomcat/shared/classes/alfresco-global.properties

####### ONLYOFFICE INTEGRATION ####### 
onlyoffice.url=https://onlyoffice.server.name/
onlyoffice.token=mysecret

I've got and Onlyoffice already running with Owncloud

this is the part of default.json:

  "secret": {
        "browser": {
          "string": "mysecret",
          "file": "",
          "tenants": {}
        },
        "inbox": {
          "string": "mysecret",
          "file": "",
          "tenants": {}
        },
        "outbox": {
          "string": "mysecret",
          "file": ""
        },
        "session": {
          "string": "mysecret",
          "file": ""
        }
      },

but when I try to modify the doc from Alfresco I receive this:;

![alfresco onlyoffice](https://user-images.githubusercontent.com/29924678/44710755-26187000-aaad-11e8-8c7e-9f8ccc984522.PNG)


Any Idea?

EDIT: on Onlyoffice log I've got:
nodeJS - checkJwt error: docId = 18fc4de1-d256-4786-b0f4-4f7fc3b72d1f_20180822124801 name = JsonWebTokenError message = jwt must be provided token = undefined

**Comment by cetra3** [comment]
Ah, I don't think this is supported just.  

The token in this module is when OnlyOffice needs to talk to Alfresco.

The token I believe you're specifying is when clients talk to OnlyOffice.  We would probably need to include an option in the share config to support JWT.

**Comment by pixel75** [comment]
So I figured it out.

On onlyoffice I changed:
default.json

 "token": {
        "enable": {
          "browser": true,
          "request": {
            "inbox": true,
            "outbox": true
          }
        },

to
 "token": {
        "enable": {
          "browser": false,
          "request": {
            "inbox": false,
            "outbox": false
          }
        },
now it is working.
