### ISSUE TITLE
OnlyOffice window

### ISSUE THREAD

**Issue by iwkse** [cetra3/onlyoffice-alfresco#2]
Hi,
I'm not sure if I can't find it, but how to return to Alfresco after you edit in OnlyOffice? If the only way is closing the window or pressing the back button, maybe it would be better to open OnlyOffice in a new tab?

Regards

**Comment by cetra3** [comment]
You can click the "back" button currently.  You can open it in a new table by middle-clicking the action.  It would possibly make sense to include a "back to Alfresco" button. or a "View Document Details" button.

**Comment by iwkse** [comment]
Yes I was doing like that but I thought of opening in a new tab (aka middle-clicking) would be nicer. I was searching if there's a way to allow an action to act like this but I haven't found much till now.

**Comment by cetra3** [comment]
Happy to accept a pull request for this, or I might be able to update it at the end of the month.  Will leave this ticket open though

**Comment by iwkse** [comment]
Ok, I will see if I find a way with opening an action on a new tab and send you a pull request

**Comment by iwkse** [comment]
Just sent a pull request, let me know

**Comment by cetra3** [comment]
Resolved by this pull request: https://github.com/cetra3/onlyoffice-alfresco/pull/3
