### ISSUE TITLE
OnlyOffice 5.4

### ISSUE THREAD

**Issue by jmoest** [cetra3/onlyoffice-alfresco#27]
Hi,
Is a new version of this connector for onlyOffice 5.4 planned?
Thank you

**Comment by sergefedorow** [comment]
Connector works with Onlyoffice Document Server 5.4.

**Comment by jmoest** [comment]
I notice some issues with users authentification which appear as anonymous.
But maybe it depend of my alfresco version (5.2)

**Comment by cetra3** [comment]
This addin works with version 5.2, but have not tested with 5.4, but should not have any issues.

Happy to accept a PR if there are changes needed for 5.4.
