### ISSUE TITLE
The document shows that xx is editing this document in ONLYOFFICE, and the document is locked. 

### ISSUE THREAD

**Issue by kalvinGit** [cetra3/onlyoffice-alfresco#31]
The document shows that xxx is editing this document in ONLYOFFICE, and the document is locked. 
Why can another user edit this document?This is a bug?
How to solve this problem?Please help me, thank you!

**Comment by cetra3** [comment]
Onlyoffice supports [co-editing of a document](https://api.onlyoffice.com/editors/coedit) meaning one or more people can edit it at the same time, so not a bug.
