### ISSUE TITLE
Integration doesn't seem to be stable

### ISSUE THREAD

**Issue by iwkse** [cetra3/onlyoffice-alfresco#5]
Hi Peter, I'm testing the integration in these days and I notice it doesn't really work for me. It seems to work randomly, sometimes it does and other times not.
More specifically what doesn't work is the collaborative editing, the documents are always opened in OnlyOffice but only sometimes it's possible to see the person icons showing there's people editing and when it doesn't work it also doesn't save properly. When it's saved changes are not committed to Alfresco. I'm trying to debug and see what is wrong with that.

Did you use the document server docker?

A way that seems to work to reproduce this issue is to enter a document with a couple of users, do some editing save, close documents and reopen again. The first time seems to work but than it stops.

**Comment by cetra3** [comment]
So there is a timeout of 10 seconds before changes are committed to Alfresco, which is an OnlyOffice thing.  For this period of time the document is locked.  Alfresco waits until the callback before saving.

I'd be interested in seeing the logs of the callback handler and seeing whether onlyoffice is communicating back.  You can see the interaction by adding the following to your log4j properties file:

```
log4j.logger.com.parashift=debug
```

**Comment by iwkse** [comment]
Yes I was reading that part of 10 seconds..but it's not related to that. Ok I will try that and let you know in minutes
[edit]
About saving yes, but there's that issue with not showing the icon with the list of users and also the notification to save for a new version available

**Comment by iwkse** [comment]
What comes to my eyes as first is this: 

```
2015-11-05 23:03:26,714 DEBUG [com.parashift.onlyoffice.CallBack] [http-apr-8080-exec-2] Document open for editing, locking document
2015-11-05 23:03:26,719 ERROR [org.springframework.extensions.webscripts.AbstractRuntime] [http-apr-8080-exec-2] Exception from executeScript - redirecting to status template error: The node (id: 5fa74ad3-9b5b-461b-9df5-de407f1f4fe7) could not be locked since it is already locked by another user.
org.alfresco.service.cmr.lock.UnableToAquireLockException: The node (id: 5fa74ad3-9b5b-461b-9df5-de407f1f4fe7) could not be locked since it is already locked by another user.
```

maybe it's needed a check to verify if the document is already locked and avoid to lock it?

**Comment by iwkse** [comment]
this instead are the callbacks:

```
2015-11-05 23:02:37,758 DEBUG [com.parashift.onlyoffice.Prepare] [http-apr-8080-exec-7] {
   "callbackUrl": "http://iwkse.homeunix.org/alfresco/s/parashift/onlyoffice/callback?nodeRef=workspace://SpacesStore/5fa74ad3-9b5b-461b-9df5-de407f1f4fe7&alf_ticket=TICKET_xxx",
   "docTitle": "budget.xls",
   "docUrl": "http://iwkse.homeunix.org/alfresco/s/api/node/content/workspace/SpacesStore/5fa74ad3-9b5b-461b-9df5-de407f1f4fe7?alf_ticket=TICKET_xxx",
   "key": "5fa74ad3-9b5b-461b-9df5-de407f1f4fe7_20151105225516",
   "onlyofficeUrl": "http://onlyoffice.foo.org/"
}
2015-11-05 23:02:52,074 DEBUG [com.parashift.onlyoffice.CallBack] [http-apr-8080-exec-9] Received JSON Callback
2015-11-05 23:02:52,077 DEBUG [com.parashift.onlyoffice.CallBack] [http-apr-8080-exec-9] {
   "key": "5fa74ad3-9b5b-461b-9df5-de407f1f4fe7_20151105225516",
   "status": 1,
   "url": "",
   "users": ["sal"]
}
2015-11-05 23:02:52,077 DEBUG [com.parashift.onlyoffice.CallBack] [http-apr-8080-exec-9] Document open for editing, locking document
2015-11-05 23:03:19,826 DEBUG [com.parashift.onlyoffice.Prepare] [http-apr-8080-exec-6] Sending JSON prepare object
2015-11-05 23:03:19,828 DEBUG [com.parashift.onlyoffice.Prepare] [http-apr-8080-exec-6] {
   "callbackUrl": "http://iwkse.homeunix.org/alfresco/s/parashift/onlyoffice/callback?nodeRef=workspace://SpacesStore/5fa74ad3-9b5b-461b-9df5-de407f1f4fe7&alf_ticket=TICKET_xxx",
   "docTitle": "budget.xls",
   "docUrl": "http://iwkse.homeunix.org/alfresco/s/api/node/content/workspace/SpacesStore/5fa74ad3-9b5b-461b-9df5-de407f1f4fe7?alf_ticket=TICKET_xxx",
   "key": "5fa74ad3-9b5b-461b-9df5-de407f1f4fe7_20151105230252",
   "onlyofficeUrl": "http://onlyoffice.foo.org/"
}
2015-11-05 23:03:26,712 DEBUG [com.parashift.onlyoffice.CallBack] [http-apr-8080-exec-2] Received JSON Callback
2015-11-05 23:03:26,714 DEBUG [com.parashift.onlyoffice.CallBack] [http-apr-8080-exec-2] {
   "key": "5fa74ad3-9b5b-461b-9df5-de407f1f4fe7_20151105230252",
   "status": 1,
   "url": "",
   "users": ["admin"]
}
```

**Comment by cetra3** [comment]
Ok, I have noticed a couple of things that may need resolving.

First is the lock service appears to update the modification date, which means that the key is no longer unique.

Second is, the callback for status 1 is called more than once, so we need to check for the lock first before trying to lock again.

I'll give it a shot here and see if I can resolve these issues.

**Comment by iwkse** [comment]
Yes..I was noticing that about the key being different. About the lock I was trying here, I think it works having like

```
import org.alfresco.service.cmr.lock.LockStatus;
...
 LockStatus lockStatus;
...
 if (lockService.getLockStatus(nodeRef) != lockStatus.LOCKED) {
                    lockService.lock(nodeRef, LockType.WRITE_LOCK);
                }
```

By the way..what the @Autowired annotation stands for?

**Comment by cetra3** [comment]
I've got a fix in place for the locking already, similar to yours, just working on the second issue (which is harder to solve) and will push both changes up soon.

`@Autowired` makes dependency injection a bit less verbose, rather than having to use setter methods for all services, and define the beans in XML, you can just use annotation-based spring components. The `onlyoffice-context.xml` file is a lot smaller.

**Comment by iwkse** [comment]
Thanks great, looking forward to that. Thanks for the clarification

**Comment by cetra3** [comment]
Should be resolved in `1.0.2`: https://github.com/cetra3/onlyoffice-alfresco/releases/tag/1.0.2.   Can you test and get back to me if there are issues.

**Comment by iwkse** [comment]
Thanks! That's surely a lot better. It makes the same issue only if you try to edit while the document is locked eg. 
- userA enter
- userB enter
- both userA and userB close the document
- both userA and userB reopen it without waiting 10 seconds

I think this is not an issue as far as we know there's such time to wait

**Comment by cetra3** [comment]
The lock should stay on there until there's an update registered from the document server.  I think the better solution will be to use another field besides modification date to detect changes, as the modification date can be updated by too many things.

I'll close this task off for now though

**Comment by iwkse** [comment]
I see. Why not using just the node id?
Mm.. I think I got it. You're using the modification date, changed when there's a Save to detect if there's a change but such date is updated not only by that

**Comment by cetra3** [comment]
OnlyOffice relies on the key being changed to determine that it's a different document, using the Node ID won't inform OnlyOffice of changes.

Node ID is used already alongside the modification date.  If you just used the Node ID and not the modification date, then OnlyOffice will retain the document it first saw, so will always use the initial version.

Unfortunately there's no real easy way to check content changes appropriately via Alfresco without adding in something like a checksum on the file, which is computationally expensive, or by managing it manually I.e, increment some number when the document is finally saved back.  You can't rely on the version number either, as some documents aren't versioned.

**Comment by iwkse** [comment]
I understand now. Another way maybe could be to disable the versionable aspect, but than you lose such capability

**Comment by cetra3** [comment]
Yeah, the ideal solution is to add an aspect which increments a number only when it's finally saved back from OnlyOffice.  This involves a couple of changes and an extra content model definition.

It's a weird edge case, but I might find time to do this soon.

**Comment by iwkse** [comment]
Ah that's cool!
