### ISSUE TITLE
Content modified activity

### ISSUE THREAD

**Issue by iwkse** [cetra3/onlyoffice-alfresco#6]
Hi,
I've just noticed when a document is modified with OnlyOffice there's not a notification on the activity. Shouldn't it work out of the box?

**Comment by cetra3** [comment]
It should, but we use a pretty low level api to update the content. This may not trigger an activity update. Would need some investigation into this

**Comment by iwkse** [comment]
Ah, I understand. I will give some test and write here if I get something useful.

**Comment by iwkse** [comment]
Hi,
Actually I've tested this and the activity message seems to be sent, but it says about the document being viewed. It would be correct to have instead, the document has been modified.
Did you have time to test that?

**Comment by cetra3** [comment]
No I haven't had time to look at this yet.  I suspect the activity service isn't hooked with the level of code we're using.

**Comment by cetra3** [comment]
If anyone has time to do this soon:

Need to add a handler into the activity service to post an activity of type `ActivityType.FILE_UPDATED` using method `activityPoster.postFileFolderActivity`

**Comment by iwkse** [comment]
I will take a look at this if I have some time. It's not really trivial as it needs to be detected the site name (in case the file is within a site) or something else.

**Comment by douglascrp** [comment]
@iwkse @cetra3 I was able to fix this issue, but I was working against the version 1.1.0, and not against the master branch.
The changes are on my fork, at https://github.com/dgcloud/onlyoffice-alfresco/tree/1.1.0

Please, review it, and merge it if you find it useful.

As soon as I find the time, I will test the changes against the master branch, but for that, we will have to upgrade our server.

**Comment by cetra3** [comment]
Nice! I think that should be compatible with master on a first glance, do you have time to submit a PR?

**Comment by douglascrp** [comment]
@cetra3 I tried to do so today in the morning, but I was not able to create a PR against an old tag.
This is why I sent the link to you. If you know how to do that, please, let me know.

I considered integrating the change in the master branch, but as I had just a few minutes left and gradle was showing me some errors, I could not finish it at the time.

**Comment by cetra3** [comment]
No worries.  I have [committed](https://github.com/cetra3/onlyoffice-alfresco/commit/d858ee2ecaea3bc7e6bcb7507a093c055424ff5e) it with a couple of minor adjustments.  Thanks @douglascrp !

**Comment by iwkse** [comment]
@douglascrp great! thank you!
