### ISSUE TITLE
PK ############

### ISSUE THREAD

**Issue by iwkse** [cetra3/onlyoffice-alfresco#8]
Hi,
suddenly I'm having this weird error when I click and save a document. After waiting the time to be written in Alfresco, the file is damaged and inside there's on like written:

PK ##################

Do you have an idea about what could be?

**Comment by cetra3** [comment]
I have not seen this before.  Is this for all files or just some?

**Comment by iwkse** [comment]
It seems all files. I've tried with odt and docx, it has the same issue. I've restarted Alfresco and also the docker but still the same. I've also created a new container but the same thing. Odd.

**Comment by cetra3** [comment]
It might be another module or other configuration item you have.  Also would be worthwhile ensuring that the two servers can still talk to eachother.

Otherwise if you can find a way of providing instructions to replicate this, then we can work through it.

**Comment by iwkse** [comment]
I've seen weird things but this is probably the biggest. Nothing changed on the server but it suddenly stopped to work. The only thing I did, but this was a week ago was to upgrade the docker-engine to latest version (1.9.2). But after that issue I've also completely grabbed the original docker image and I still get the same issue. I'm not sure if PK refers to some public key, I've checked in the code and there's something related to pk and this. I've also opened a ticket to docker-documentserver.
For now I can just say it's all very odd.

**Comment by cetra3** [comment]
Are you using SSL?

If you have debug enabled, you should be able to see the callback URL that gets sent to Alfresco from OnlyOffice.  There is a JSON submission that will include a `url`.  We use this to indicate where Alfresco can download the file.  There will also be a log entry that starts with `Retrieving URL:`

If you download the file manually from the URL, is the file OK?

**Comment by iwkse** [comment]
Not using SSL. The issue is not with Alfresco and the integration but OnlyOffice itself. The file is already corrupted in OnlyOffice after saving it. Must be something wrong in OnlyOffice which is odd..because as I said, to be sure, I got a brand new docker image.

**Comment by cetra3** [comment]
Ok, that is strange.  The docker image I've used is:

```
docker pull onlyoffice/documentserver
latest: Pulling from onlyoffice/documentserver
Digest: sha256:937ede04177e8f6e6d142eed53554947526ce8c8af718ca0cc8988b300a12c7a
Status: Image is up to date for onlyoffice/documentserver:latest
```

And docker:

```
Docker version 1.7.1, build 786b29d
```

Happy to close this issue? Since this doesn't appear to be related to the integration

**Comment by iwkse** [comment]
Thanks for the info. I will see if something changed and it's an issue with a different pulled image.
Yes, it's definitely not related to the integration. OnlyOffice doesn't reply though or do it very slowly,
https://github.com/ONLYOFFICE/Docker-DocumentServer/issues/4
